Logo = ''
DJ_name = 'Alexx'
Preferred_name = 'Alexx'
Pronouns = 'Any'
Discord = ''

[Genres]
Primary = ['hyperpop', 'breakcore']
Secondary = ['Pop', 'DnB']

[Social]
Twitter = 'https://twitter.com/apuppyonline'