Logo = './img/avian_invasion.png'
DJ_name = 'Avian Invasion'
Preferred_name = 'B1RD'
Pronouns = 'He/Him'
Discord = ''

[Genres]
Primary = ['Progressive House']
Secondary = ['MH&T', 'Trance', 'Techno', 'Dance Pop']

[Social]
Twitter = ''