Logo = './img/blazethelion.png'
DJ_name = 'Blazethelion'
Preferred_name = 'Blaze'
Pronouns = 'He/Him'
Discord = ''

[Genres]
Primary = ['DnB']
Secondary = ['Midtempo', 'Bass House', 'Trance']

[Social]
Twitter = ''