Logo = ''
DJ_name = 'CyberCanine'
Preferred_name = 'Chrissy'
Pronouns = 'She/Her'
Discord = ''

[Genres]
Primary = ['Trance', 'Hardcore']
Secondary = ['Vocaloid', 'House', 'DnB']

[Social]
Twitter = 'https://twitter.com/CyberCanine'