Logo = ''
DJ_name = 'DJ Hyperion'
Preferred_name = 'Hyperion'
Pronouns = 'He/Him'
Discord = ''

[Genres]
Primary = ['Trance', 'Psytrance']
Secondary = []

[Social]
Twitter = 'https://twitter.com/DJHyperionPup'