Logo = ''
DJ_name = 'DJ Nightfire'
Preferred_name = 'Nightfire'
Pronouns = 'He/Him'
Discord = ''

[Genres]
Primary = ['Mainstage', 'Electro House', 'Bass House']
Secondary = ['Tribal House, Trance, DnB']

[Social]
Twitter = 'https://twitter.com/DJNightfirex'