Logo = ''
DJ_name = 'DJSeaJay'
Preferred_name = 'SeaJay'
Pronouns = ''
Discord = ''

[Genres]
Primary = ['Melodic Dubstep', 'Melodic Hardstyle', 'Dubstep']
Secondary = ['Swing', 'Funk', 'Kawaii Bass']

[Social]
Twitter = ''