Logo = ''
DJ_name = 'DJ Tronix'
Preferred_name = 'Soto'
Pronouns = 'He/Him'
Discord = ''

[Genres]
Primary = ['DnB', 'Hardstyle']
Secondary = []

[Social]
Twitter = 'https://twitter.com/Wolfgaming2016G'