Logo = ''
DJ_name = 'DJ Volatile'
Preferred_name = 'Volatile'
Pronouns = 'He/Him/She/Her/They/Them'
Discord = ''

[Genres]
Primary = ['Deathstep', 'Minatory']
Secondary = ['Tearout', 'Melodic Dubstep']

[Social]
Twitter = 'https://twitter.com/omfghellovrc'