Logo = ''
DJ_name = 'GHSTSKY'
Preferred_name = 'Cole'
Pronouns = 'He/She/They'
Discord = ''

[Genres]
Primary = ['Dubstep', 'House', 'DnB', 'Hardstyle']
Secondary = ['Trance', 'Techno']

[Social]
Twitter = 'https://twitter.com/colehusky'