Logo = ''
DJ_name = 'KT - 77'
Preferred_name = 'Kyuu'
Pronouns = 'He/Him'
Discord = ''

[Genres]
Primary = ['Trance', 'Hard Trance', 'Techno', 'Hard Techno']
Secondary = ['Hard House', 'Mainstage', 'Hard Dance']

[Social]
Twitter = ''