Logo = './img/leon13522gaming.png'
DJ_name = 'leon13522gaming'
Preferred_name = 'leon13522gaming'
Pronouns = 'He/Him'
Discord = ''

[Genres]
Primary = ['Hardcore', 'Uptempo', 'Hardstlye']
Secondary = ['DnB']

[Social]
Twitter = 'https://twitter.com/leon13522gaming'