Logo = ''
DJ_name = 'Mellow'
Preferred_name = 'Mellow'
Pronouns = 'He/Him'
Discord = ''

[Genres]
Primary = ['Midtempo', 'Dubstep', 'DnB']
Secondary = ['liquid', '140', 'Breakcore']

[Social]
Twitter = ''