Logo = ''
DJ_name = 'Morganite'
Preferred_name = 'Morganite'
Pronouns = 'She/They'
Discord = ''

[Genres]
Primary = ['Psytrance']
Secondary = ['Techno', 'DnB', 'House']

[Social]
Twitter = 'https://twitter.com/morganitenoises'