Logo = ''
DJ_name = 'Sagru'
Preferred_name = 'Sagru'
Pronouns = 'He/She/They/Them'
Discord = ''

[Genres]
Primary = ['DnB', 'Liquid']
Secondary = ['Trance', 'Psytrance', 'Progressive House']

[Social]
Twitter = 'https://twitter.com/Nightshadow115'