Logo = ''
DJ_name = 'Scalie Bloke'
Preferred_name = 'Dad'
Pronouns = 'Skibidi/Toilet'
Discord = ''

[Genres]
Primary = ['Any']
Secondary = ['Any']

[Social]
Twitter = 'https://twitter.com/ScalieBloke'