Logo = './img/schlick.png'
DJ_name = 'Schlick'
Preferred_name = 'Schlick'
Pronouns = 'He/Him'
Discord = ''

[Genres]
Primary = ['Techno']
Secondary = ['Hard Techno']

[Social]
Twitter = 'https://twitter.com/schlickwolf'