Logo = ''
DJ_name = 'Sherbert Fox'
Preferred_name = 'Sherbert'
Pronouns = 'They/Them'
Discord = ''

[Genres]
Primary = ['Tech House', 'Garage House']
Secondary = ['Bass House', 'DnB', 'Trance']

[Social]
Twitter = 'https://twitter.com/SherbertFox'