Logo = './img/shizukavr.png'
DJ_name = 'ShizukaVR'
Preferred_name = 'Shizu'
Pronouns = 'She/Her'
Discord = ''

[Genres]
Primary = ['Dubstep', 'House', 'DnB']
Secondary = ['Techno', 'Hardstyle', 'Trance']

[Social]
Twitter = 'https://twitter.com/shizukavr'