Logo = ''
DJ_name = 'Stormy'
Preferred_name = 'Stormy'
Pronouns = 'He/Him'
Discord = ''

[Genres]
Primary = ['Big Room', 'Hard Dance']
Secondary = []

[Social]
Twitter = 'https://twitter.com/StormyWolf295'