Logo = './img/strawberry_protato.png'
DJ_name = 'Strawberry Protato'
Preferred_name = 'Strawbs'
Pronouns = 'She/Her'
Discord = ''

[Genres]
Primary = []
Secondary = []

[Social]
Twitter = 'https://twitter.com/strawbsprotato'