Logo = './img/strawberry_protato.png'
DJ_name = 'Strawberry Protato'
Preferred_name = 'Strawbs'
Pronouns = 'She/Her'
Discord = ''

[Genres]
Primary = ['Chill House', 'Trippy Grooves', 'Filthy Funky Beats', 'Breaks', 'Bass']
Secondary = ['Chill']

[Social]
Twitter = 'https://twitter.com/strawbsprotato'