Logo = ''
DJ_name = 'Striker'
Preferred_name = 'Skye'
Pronouns = 'He/Him'
Discord = ''

[Genres]
Primary = ['Tech House']
Secondary = ['House', 'EDM', 'Electro Pop', 'Dance']

[Social]
Twitter = 'https://twitter.com/StrikerMusic89'