Logo = ''
DJ_name = 'Swolf'
Preferred_name = 'Swolf'
Pronouns = 'He/Him'
Discord = ''

[Genres]
Primary = ['Pop House', 'Dance', 'Funky House']
Secondary = ['Trance', 'Hard Dance', 'Breaks', 'Happy Hardcore', 'Donk']

[Social]
Twitter = 'https://twitter.com/Swolf'