Logo = './img/t1m3k33p3r.png'
DJ_name = 'T1M3K33P3R'
Preferred_name = 'Jack'
Pronouns = 'He/Him'
Discord = ''

[Genres]
Primary = ['Heavy Bass']
Secondary = []

[Social]
Twitter = 'https://twitter.com/jackdurrmusic'