Logo = './img/vapor.png'
DJ_name = 'Vapor'
Preferred_name = 'Angiee'
Pronouns = 'She/Her'
Discord = ''

[Genres]
Primary = ['Colour Bass', 'Dubstep']
Secondary = ['DnB', 'Bass House', 'Midtempo', 'Trap']

[Social]
Twitter = 'https://twitter.com/AngieeCandyy'